version: 1.0.{build}

environment:
  nodejs_version: "6"
  NETWORK: "mainnet"
  AWS_ACCESS_KEY_ID:
    secure: NoU3qXx0B+48v7PY3RzHrBrSqd4x/3dcJv8WwUzCNyE=
  AWS_SECRET_ACCESS_KEY:
    secure: TIIz2Xtcn63BxDJ9h+2Uj73vJrfmImtlZHh0y2YxGIpwu3eRV9OA+1jhDiG2zPch
  CERT_PASS:
    secure: 9tjYxdz1fqibx1WOrP5yn32iwbEXeYx+Btb5QJqHvMO4Ng2/yUtPi00/ZMXihFWV
  # Avoid long paths on Windows
  STACK_ROOT: "c:\\sr"

build: off

cache:
  - C:\sr -> installers/luxcoin-installer.cabal
  - C:\sr -> installers/stack.yaml

install:
  - ps: Install-Product node $env:nodejs_version x64
  - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER aws s3 cp --region eu-central-1 s3://luxcore-private/luxcore-windows-certificate-2.p12 C:/luxcore-windows-certificate.p12

test_script:
  - scripts\build-installer-win64.bat %APPVEYOR_BUILD_VERSION% master

artifacts:
  - path: release\win32-x64\Luxcore-win32-x64
    name: Luxcore Electron application
    type: zip
  - path: installers\luxcore-win64-*-installer.exe
    name: Luxcore Win64 Installer
  - path: node_modules\luxcore-client-api\build-id
    name: luxcoin-sl-build-id
